// IPhreeqcCOM.idl : IDL source for IPhreeqcCOM
//

// This file will be processed by the MIDL tool to
// produce the type library (IPhreeqcCOM.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(2539a7ee-93f4-4c9e-b875-e194168d4cd0),
	version(1.0),
]
library IPhreeqcCOMLib
{
	importlib("stdole2.tlb");
};

